### ISSUE TITLE
chutiya bnda

### ISSUE THREAD

**Issue by Tejvansh1** [Tejvansh1/hi#3]
Oye lodu... Btaya nhi fir kaisa hai?!!

_Originally posted by @Falana-G in https://github.com/Tejvansh1/hi/pull/2#discussion_r1480926128_

**Comment by Falana-G** [comment]
> ```
>           Oye lodu... Btaya nhi fir kaisa hai?!!
> ```
> 
> _Originally posted by @Falana-G in [#2 (comment)](https://github.com/Tejvansh1/hi/pull/2#discussion_r1480926128)_

Issue kya hai be!!! LODU hai toh Lodu hi kahunga!!
